name: Triggered by Pull Request Review
on:
  pull_request_review:
    
jobs:
  rerun_pull_request_job_1:
    name: Rerun pull request job
    runs-on: deere-ubuntu-latest
    steps:
      - run: echo hit
