name: Triggered by Pull Request Review
on:
  pull_request_review:
    
jobs:
  rerun_pull_request_job_1:
    name: Rerun pull request job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Extract Job ID
        run: |
          # Fetch link to job to rerun
          run_link="$(gh pr checks \
            --json name,link \
            --jq '
              .[]
              | select(.name == "Job 1")
              | .link
          ')"
          echo "URL for job to rerun: $run_link"

          # Extract job ID from URL
          job_id="${${run_link#*/runs/}%/job/*}"
          echo "JOB_ID=$job_id}" >> "$GITHUB_ENV"
      - name: Rerun approval check job
        run: gh run rerun "$JOB_ID"
